spring:
  application:
    name: notifier-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

solar:
  idempotency:
    ttl-seconds: ${IDEMPOTENCY_TTL_SECONDS:86400}
